### ISSUE TITLE
CMake generation error

### ISSUE THREAD

**Issue by magnusjjj** [alandtse/CommonLibF4#16]
Hi!

There is an error in tests/cmakelists.txt

src/BSTHashMap.cpp

needs to be

src/RE/B/BSTHashMap.cpp

**Comment by magnusjjj** [comment]
Oh, and on compile

C:\Users\Tuxie\Source\Repos\CommonLibF4ng\build\debug-msvc-vcpkg-all\ninja : error : dependency cycle: CommonLibF4/CMakeFiles/CommonLibF4.dir/cmake_pch.cxx.obj -> CommonLibF4/CMakeFiles/CommonLibF4.dir/CXX.dd -> CommonLibF4/CMakeFiles/CommonLibF4.dir/src/F4SE/API.cpp.obj.ddi -> CommonLibF4/CMakeFiles/CommonLibF4.dir/cmake_pch.cxx.pch -> CommonLibF4/CMakeFiles/CommonLibF4.dir/cmake_pch.cxx.obj

Don't know how to fix that one.

**Comment by alandtse** [comment]
Thanks for the first issue. I've fixed it. Not sure how you got to the dependency cycle. Please open a new issue with some details.

**Comment by alandtse** [comment]
BSTHashMap issue fixed with latest commit.
